### ISSUE TITLE
LoC tracking + conditionally compiled code

### ISSUE THREAD

**Issue by cdstanford** [PLSysSec/cargo-scan#32]
Add code in `scanner` to gather stats about the total amount of code skipped (in LoC) vs. scanned.

- [x] In addition to macros, skip platform-specific and conditionally compiled code
- [x] Add a count of skipped # of lines and processed # of lines to scanner and scan results
- [x] Add LoC for macros and conditionally compiled code throughout scanner
- [x] Add LoC for effects
- [ ] Add LoC for transitive effects: using --scan binary
- [ ] In auditing toolchain: report skipped blocks of code in a separate set of code blocks for the user to audit
- [ ] collect summary in `scan.py`

**Comment by cdstanford** [comment]
Copying here from Lydia: an example for cfg-d out code in `rand`: `data/packages/rand/src/rngs/xoshiro128plusplus.rs`

which is inactive due to:
```
#[cfg(all(feature = "small_rng", not(target_pointer_width = "64")))]
mod xoshiro128plusplus;
```
in `data/packages/rand/src/rngs/mod.rs`

**Comment by cdstanford** [comment]
closing as out of date -- I think this is mostly done, the parts that are not done we will get to when we run some experiments.
