### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by cdstanford** [PLSysSec/cargo-scan#47]
From discussion today,

- [x] Make `audit` the default binary, ~~rename `scan` to `scan_csv`~~
- [x] For `audit`: add a default argument for `<AUDIT_FILE_PATH>`
- [x] Provide a bit more info to stdout: continuing an existing audit, saving audit to <file> ,etc. (tool already does a good job of some of this, telling you it's loading an audit file, creating a new audit file)
- [x] Provide a way to run `audit` and create a new scan, listing all effects (without auditing -- matching the behavior of scan)

Currently the `-r` flag is supposed to do the third thing, but I can't quite get it to do what I want. Maybe the solution is just, if the audit file doesn't exist, create it with the default scan?

```
caleb@caleb-mac cargo-scan % cargo run --bin audit data/test-packages/fns-closures audit.audit2 -r
    Finished dev [unoptimized + debuginfo] target(s) in 0.40s
     Running `target/debug/audit data/test-packages/fns-closures audit.audit2 -r`
Error: Audit file to review doesn't exist
caleb@caleb-mac cargo-scan % 
caleb@caleb-mac cargo-scan % 
caleb@caleb-mac cargo-scan % cargo run --bin audit data/test-packages/fns-closures audit.audit3 -r
    Finished dev [unoptimized + debuginfo] target(s) in 0.53s
     Running `target/debug/audit data/test-packages/fns-closures audit.audit3 -r`
Error: Audit file to review doesn't exist
```

**Comment by DavidThien** [comment]
Finished with this pending a decision on if we need to have a better output format for the preview behavior (list all effects and don't save to an audit file).

**Comment by cdstanford** [comment]
woohoo
